-- BANKS TABLE
CREATE TABLE banks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

-- REVIEWS TABLE
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review CLOB,
    rating NUMBER,
    date DATE,
    bank_id NUMBER,
    source VARCHAR2(50),
    processed_review CLOB,
    sentiment VARCHAR(20),
    vader_sentiment VARCHAR(20),
    label VARCHAR2(20),
    FOREIGN KEY (bank_id) REFERENCES banks(id)
);
